username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
encoding: json_ietf
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400

subscriptions:
  srl-acl-statistics:
    mode: stream
    stream-mode: on-change
    paths:
      - /acl/acl-filter[name=*][type=ipv6]/entry[sequence-id=5]/description
      - /acl/acl-filter[name=*][type=ipv6]/entry[sequence-id=6]/description
      - /acl/acl-filter[name=*][type=ipv6]/entry[sequence-id=7]/description
      - /acl/acl-filter[name=*][type=ipv6]/entry[sequence-id=100]/description
      - /acl/interface[interface-id=*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=5]/statistics/matched-packets
      - /acl/interface[interface-id=*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=6]/statistics/matched-packets
      - /acl/interface[interface-id=*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=7]/statistics/matched-packets
      - /acl/interface[interface-id=*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=100]/statistics/matched-packets

outputs:
  file_output:
    type: file
    filename: /data/acl_statistics.json
    format: json
    split-events: true

  prom-output:
    type: prometheus
    listen: :9273  
