username: admin
password: NokiaSrl1!
insecure: false
skip-verify: true
timeout: 10s

targets:
  srlswitch:
    address: srlswitch:57400

subscriptions:
  srl-system-performance:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /platform/control[slot=*]/cpu[index=all]/total
        
  srl-if-stats:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      - /interface[name=ethernet-1/*]/statistics
      - /interface[name=ethernet-1/*]/traffic-rate
  
  srl-acl-statistics:
    mode: stream
    stream-mode: sample
    sample-interval: 5s
    paths:
      
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=1]/statistics/
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=2]/statistics/
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=3]/statistics/
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=4]/statistics/
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=5]/statistics/
      - /acl/interface[interface-id=ethernet-1/*]/input/acl-filter[name=*][type=ipv6]/entry[sequence-id=100]/statistics/

outputs:
  
  prom-output:
    type: prometheus
    listen: :9273  
    
